vtex-apps/storefront-permissions

- CHANGELOG.md
- node/directives/withSender.ts
- node/resolvers/index.ts
- node/typings.d.ts
- node/yarn.lock
- policies.json
- vtex.session/configuration.json
- Policy for other apps to call this app's GraphQL routes
- `organization`, `costCenter`, `collections` are now populated in user's session
> Add GraphQL policy, populate fields in user's session

- CHANGELOG.md
- node/package.json
- node/resolvers/Mutations/Roles.ts
- node/resolvers/Queries/Users.ts
- node/yarn.lock
If two or more modules (i.e. apps) defined features (i.e. permissions) using the storefront-permissions builder, only one module's features would show up when querying the current user's permissions. Essentially, when a new module was added into the mix, only the new module's permissions would be returned. 
This was caused by a bug in a single line of code, where instead of saving the combined array of all modules and features, only the "new" module and its features were being saved. See  `node/resolvers/Mutations/Roles.ts` for the fixed line of code.
Linked here: https://quotes--sandboxusdev.myvtex.com/admin/app/storefront-permissions/role/f2a38526-f3bd-11eb-82ac-12fda6a1f41f
Note that permissions are correctly …
> [B2BORG-39] Fix bug when storing features from multiple modules

- CHANGELOG.md
- node/resolvers/index.ts
If a user is in an inactive organization, we decided that they should be unable to login. This PR implements that behavior by checking the organization's status while modifying the user's session and throwing a 403 Forbidden error if the status is equal to "inactive".  
Linked in https://quotes--sandboxusdev.myvtex.com
Interestingly, when the app throws an error and login is blocked, the session request is retried on every page reload. The end result is still the same, but it's something to be aware of.
> [B2BORG-19] Prevent login for inactive orgs

- CHANGELOG.md
- manifest.json
- node/resolvers/Queries/Users.ts
`checkUserPermissions` query was throwing an error if the user's role had no enabled permissions for the app making the request. For example, the Buyer role has no enabled permissions for `vtex.b2b-organizations`, but the query should still be able to be used to query the user's role. This PR allows the query to succeed in this scenario (the `permissions` field will be an empty array).
Linked in https://quotes--sandboxusdev.myvtex.com
> Don't throw error if user's role has no enabled permissions

- CHANGELOG.md
- node/resolvers/Mutations/Users.ts
Previously, an organization admin was able to use the "Add User" form to add the same user multiple times. They could add the same user with two different roles, or put the same user in two different cost centers, etc. Behind the scenes, storefront-permissions was creating two records that both pointed to the same CL ID. This was because there was no validation to see if the user (specifically, the email address) already existed in the storefront-permissions MD table.
This PR adds validation for this. If the app finds an existing record for the "new" user's email, it will update that record rather than creating a brand new record.
Linked in https://quotes--sandboxusdev.myvtex.com . Try going to My Account - My …
> Check if email already exists in MD when adding a new user

- CHANGELOG.md
- docs/README.md
- manifest.json
- node/resolvers/index.ts
When an Account indirectly depend o Storefront Permissions, it unnecessarily triggers actions on the Session
This version adds a new App Setting that can be used to disable the session watcher
Access the App Settings from the admin [/admin/apps/vtex.storefront-permissions@1.x/setup/](https://wender--sandboxusdev.myvtex.com/admin/apps/vtex.storefront-permissions@1.x/setup/)
Make sure it's ON
Log in using **wender.lima@gmail.com** `Wender@123`
Access [https://wender--sandboxusdev.myvtex.com/api/sessions?items=*](https://wender--sandboxusdev.myvtex.com/api/sessions?items=*) to check if `storefront-permissions` namespace is defined
Log out and check the `storefront-permissions` namespace again, it should not be there …
> Added Session Watcher toggle setting

- CHANGELOG.md
- docs/README.md
- graphql/schema.graphql
- node/resolvers/Mutations/Settings.ts
- node/resolvers/Queries/Settings.ts
- node/resolvers/index.ts
When an Account indirectly depend o Storefront Permissions, it unnecessarily triggers actions on the Session
This version adds a new App Setting (vbase) that can be used to disable the session watcher
[Using GraphiQL interface ](https://wender--sandboxusdev.myvtex.com/_v/private/vtex.storefront-permissions@1.12.2/graphiql/v1?query=query%20getSessionWatcher%20%7B%0A%20%20getSessionWatcher%0A%7D%0A%0Amutation%20setSessionWatcher%20%7B%0A%20%20sessionWatcher(active%3A%20false)%0A%7D%0A&operationName=setSessionWatcher)
Run que query 
```graqhql
query getSessionWatcher {
getSessionWatcher
}
```
Make sure it is `true`
Log in using **wender.lima@gmail.com** `Wender@123`
Access …
> Added graphql session watcher

- node/resolvers/Mutations/Roles.ts
- node/resolvers/Queries/Roles.ts
- node/utils/index.ts
When the MD roles database already exists, the roles are being rewritten and the permissions are lost.
[https://artur3--b2bstoreqa.myvtex.com/admin/storefront-permissions/roles/list](https://artur3--b2bstoreqa.myvtex.com/admin/storefront-permissions/roles/list)
When the data from VB is returning empty it checks on MD if it exists then return them or the default roles.
> Fix on VB existing MD database

- CHANGELOG.md
- node/index.ts
- node/resolvers/Mutations/Users.ts
- node/resolvers/Queries/Users.ts
- node/resolvers/index.ts
Our team discussed the impersonation feature and came to the following conclusions:
- impersonation should apply the impersonated user's organization and cost center to your session
- your original role and permissions should NOT be replaced with the impersonated user's role/permissions
This PR enables the above functionality. I also made an adjustment to allow `impersonateUser` to receive a forwarded session token, so that `b2b-organizatons-graphql` can apply a permissions check before executing the mutation. 
This new version along with new versions of `b2b-organizations` and `b2b-organizations-graphql` is linked here: https://b2bsuite--sandboxusdev.myvtex.com
To impersonate a user, login as someone with …
> [PERMISSION-22] Improve impersonation feature

- CHANGELOG.md
- node/resolvers/index.ts
Fix on the shipping data attachment payload passing the **_clearAddressIfPostalCodeNotFound_** flag to null.
There was a problem with the US zip code addresses which was changing to null the street and neighborhood. 
[https://b2b--productusqa.myvtex.com/](https://b2b--productusqa.myvtex.com/)
Credentials: syed+tuesorgaoa1@bitcot.com  !Q2w#E4r%T6y&U
Add a product to the cart and proceed to checkout and finish it.
> B2BCHCKOUT-18 - Unable to make a payment in b2b store - Getting Error [PFA]

- CHANGELOG.md
- node/clients/checkout.ts
- node/resolvers/Queries/Users.ts
- node/resolvers/index.ts
- node/service.json
- node/yarn.lock
Previously this app did not support impersonation via the [telemarketing app](https://github.com/vtex-apps/telemarketing) but we had several requests to make the two systems work together.
This PR adds support for telemarketing impersonation. This solution relies on the `orderForm` to tell our app that a telemarketing impersonation session is active, by checking for a `userProfileId` and a `userType` of `callCenterOperator`. Finally, it checks if the email address in `orderForm.clientProfileData` is different from the authenticated user's email address. If all of this is true, the impersonated user's organization information will be loaded and applied to the session, the same as if our B2B impersonation feature was used.
This PR also adjusts the …
> [PERMISSION-25] Support telemarketing and join both users' permissions

- CHANGELOG.md
- node/index.ts
- node/resolvers/Queries/Users.ts
- node/resolvers/index.ts
- vtex.session/configuration.json
Recently we updated `b2b-organizations-graphql` to allow a `businessDocument` to be assigned to a cost center. This PR updates `storefront-permissions` so that if the `businessDocument` field is present:
- it will be added to the user's orderForm profile data
- the `isCorporate` profile flag will be set to `true`
- the `corporateName` profile field will be set to the name of the user's organization
Additionally, this PR optimizes the `setProfile` function so that it will be less likely to time out when called by the VTEX session hub. The function no longer awaits the resolution of the orderForm update operations, for example. Also, rather than checking the orderForm to see if there is a telemarketing impersonation session currently active, it gets this …
> [B2BORG-84] Add support for businessDocument, optimize

- .github/workflows/sonarcloud.yml
- CHANGELOG.md
- graphql/schema.graphql
- node/package.json
- node/resolvers/Mutations/Users.ts
- node/resolvers/Routes/index.ts
- node/resolvers/index.ts
- node/yarn.lock
Currently, there is a single mutation for adding & editing B2B users. This is causing some unexpected issues.
The solution was to create 2 mutations separated in order to handle the actions carefully and avoid unexpected issues.
Also, I modified the routes structure, added logging errors, and removed unnecessary variable declarations.
**Workspace Graphql Playground:**
[https://b2borg--sandboxusdev.myvtex.com/admin/graphql-ide](https://b2borg--sandboxusdev.myvtex.com/admin/graphql-ide)
**Update User** 
```graphql
mutation ($id: ID $clId: ID! $userId: ID! $roleId: ID! $orgId: ID! $costId: ID! $canImpersonate: Boolean!) {
updateUser (id:$id, clId: $clId, userId: $userId, roleId: $roleId, orgId: $orgId, costId: $costId, canImpersonate: $canImpersonate) {
id
} …
```
> [PERMISSION-23] Modify storefront permissions so that it has 2 separate mutations for adding vs updating users

- CHANGELOG.md
- node/resolvers/Routes/index.ts
- node/resolvers/Routes/utils/index.ts
- node/yarn.lock
B2B Organizations and B2B Organizations GraphQL have already been updated to allow B2B users to define a `tradeName` for their organization and a `phoneNumber` for their cost centers. This PR updates Storefront Permissions to inject these values into the user's session, if present. Also, the `setProfile` function has been refactored to pass SonarCloud's cognitive complexity check.
Linked in https://b2bsuite--sandboxusdev.myvtex.com
Log in as a user in an organization that has a `tradeName` and/or in a cost center that has a `phoneNumber`, and then go to checkout. The specified values should be added into the relevant checkout fields.
> [B2BORG-118] Add support for tradeName and phoneNumber

- CHANGELOG.md
- graphql/schema.graphql
Previously, the `getUserByEmail` query will return null for all users. This PR fix the query and make sure it returns valid id for b2b users.
In the graphql-ide of [workspace](https://b2borg--sandboxusdev.myvtex.com/admin/graphql-ide), 
test
`query CheckPermissions($email: String!) {
getUserByEmail(email: $email)
{
id
roleId
userId
clId
orgId
costId
canImpersonate
}
}`
> [B2BORG-142] Hide for b2c

- CHANGELOG.md
- manifest.json
- node/resolvers/Routes/index.ts
Error at the checkout when using multiple priceTables
[Splunk](https://vtex.splunkcloud.com/en-US/app/search/search?earliest=-3d%40d&latest=now&q=search%20index%3D*%20607ecb47-0f04-4761-bcc2-a8cb12dd0437&display.page.search.mode=smart&dispatch.sample_ratio=1&sid=1667393847.4669265_A2CD0FD4-C32E-4C6C-B6DB-20F8989F8580)
According to this [document](https://help.vtex.com/en/tutorial/configurar-price-tables-especificas-com-o-session)
> o create more than one, separate them by commas. For example: gold, silver
> Issue with priceTables separator

- CHANGELOG.md
- node/clients/checkout.ts
- node/resolvers/Routes/index.ts
- node/yarn.lock
- `setProfile` adding sku 1 to the cart to set sales channel when the cart is empty
- `setProfile` losing item attachments after login
First test: Login with cart empty. It should stop showing the product not found or with no inventory toast message after login
Second test: With products in the cart with attachments, log out, and log back in. The attachment must stay the same
[https://setprofile--pierceqa.myvtex.com/](https://setprofile--pierceqa.myvtex.com/)
> Fix losing attachments after login

- CHANGELOG.md
- node/resolvers/Routes/index.ts
Fix issue where `documentType` is set to`cpf` even for non Brazilian customers.
Link to issue: https://github.com/vtex-apps/storefront-permissions/issues/102
This is actually a workaround where we just check if the user cost center addresses and only force `documentType` to be`cpf` if one of them is in Brazil.
The proper fix (for which we will create a task to be tackled later) consists in using a library/service that returns the expected `documentType` for given country.
For now, at least we don't set `documentType` incorrectly to `cpf` anymore.
1. Login to a store with a user/organization where cost center does not have a Brazilian address
2. Create an order and check that `documentType` is not set to `cpf` and …
> Fix issue where documentType is always set to cpf

- CHANGELOG.md
- manifest.json
- node/resolvers/Mutations/Users.ts
- node/utils/metrics/changeTeam.ts
- node/utils/metrics/metrics.ts
- node/yarn.lock
Send change team action metrics to Analytics
Go to https://takeda--b2bstore005.myvtex.com, and log in with a user with access to more than one organization/cost center. Select a different organization/cost center and click "Manager Current Organization". Data should appear in Analytics after one hour or so into  "vtex"."schemaless"."b2b_suite_buyerorg_data_raw" schema
Types
```
export type ChangeTeamMetric = {
kind: 'change-team-graphql-event'
description: 'User change team/organization - Graphql'
}
export type Metric = {
name: 'b2b-suite-buyerorg-data'
account: string
} & ChangeTeamMetric
type ChangeTeamFieldsMetric = {
date: string
user_id: string
user_role: string
user_email: string
org_id: string
cost_center_id: …
```
> Change Team Metrics

- CHANGELOG.md
- node/resolvers/Queries/Roles.ts
- node/resolvers/Queries/Users.ts
- node/resolvers/Routes/index.ts
- Reduce the call to sync roles
> fix: reduce sync roles

- CHANGELOG.md
- docs/README.md
Add a small description about Session Watcher and why to use it.
> docs: Add Session Watcher intro

- CHANGELOG.md
- node/clients/Organizations.ts
- node/clients/index.ts
- node/package.json
- node/resolvers/Routes/utils/index.ts
- node/yarn.lock
- We have an integration between storefront-permissions and b2b-organizations, and it is necessary to validate authentication in the request. But for some reason the storefront-permissions can't forward the cookie headers, and the token doesn't come in b2b-organization-graphql.
So, we change the integration structure and the graphql server intermediation to use the header `x-vtex-caller` as `vtex.storefront-permissions` and allow in b2b-organizations.
- Login in the b2b store.
**Screenshots or example usage:**
> fix: adjust b2b-organizations-graphql integration

- CHANGELOG.md
- node/resolvers/Routes/index.ts
Currently when an organization's corporate document starts with letters, the first digit is removed after accessing checkout.
This PR is changing this logic to only remove special characters
Solving KI 920703
> Changed to remove special characters

- CHANGELOG.md
- node/clients/index.ts
- node/directives/checkAdminAccess.ts
- node/directives/checkUserAccess.ts
Revert latest changes as these broke multiple stores.
The following versions were deprecated: 1.40.1, 1.40.2 and 1.40.3
Current valid version: 1.40.0
> Revert auth changes due to rollback

- CHANGELOG.md
- node/clients/IdentityClient.ts
- node/directives/checkAdminAccess.ts
- node/directives/checkUserAccess.ts
- node/directives/helper.ts
- node/metrics/auth.ts
Improve logging and metrics on checkUserAccess and checkAdminAccess directives. This will help us understand how these APIs are used.
This change keeps previous authentication behavior, it just make sure to validate all provided tokens and emit metric before applying rules.
Tested calling APIs with each directive with multiple different authentication methods.
> chore: improve metrics/logs for checkUserAccess/checkAdminAccess

- CHANGELOG.md
- node/clients/Organizations.ts
- node/clients/index.ts
Provide correct tokens to the clients. More info on: [https://vtex-dev.atlassian.net/browse/B2BTEAM-1683](https://vtex-dev.atlassian.net/browse/B2BTEAM-1683)
> fix: provide correct tokens to clients

- CHANGELOG.md
- graphql/directives.graphql
- graphql/schema.graphql
- node/directives/helper.ts
- node/directives/index.ts
- node/directives/validateStoreUserAccess.ts
- node/directives/validateUserAccess.ts
- node/metrics/auth.ts
- node/resolvers/Queries/Users.ts
- node/utils/LicenseManager.ts
Added a new token validation directive. More info on: [https://vtex-dev.atlassian.net/browse/B2BTEAM-1686](https://vtex-dev.atlassian.net/browse/B2BTEAM-1686)
> fix: add token validation directive

- CHANGELOG.md
- node/directives/checkAdminAccess.ts
- node/directives/checkUserAccess.ts
- node/directives/helper.ts
- node/directives/validateStoreUserAccess.ts
- node/metrics/auth.ts
Added logic to also get tokens from headers. More info on: [https://vtex-dev.atlassian.net/browse/B2BTEAM-1733](https://vtex-dev.atlassian.net/browse/B2BTEAM-1733)
> fix: get admin token from header

- CHANGELOG.md
- node/directives/checkAdminAccess.ts
- node/directives/checkUserAccess.ts
- node/directives/helper.ts
- node/directives/validateAdminUserAccess.ts
- node/directives/validateStoreUserAccess.ts
- node/metrics/auth.ts
Remove metric and enforce new token validation. More info on: [https://vtex-dev.atlassian.net/browse/B2BTEAM-1757](https://vtex-dev.atlassian.net/browse/B2BTEAM-1757)
> fix: remove metric and enforce token validation

- CHANGELOG.md
- graphql/schema.graphql
Changing the token validation directive of some operations. More info on: [https://vtex-dev.atlassian.net/browse/B2BTEAM-1808](https://vtex-dev.atlassian.net/browse/B2BTEAM-1808)
> fix: change token validation directive of some operations

- CHANGELOG.md
- node/package.json
- node/resolvers/Routes/utils/index.ts
- node/yarn.lock
When a user has more than one organization assigned and the first registered one is inactive, the system does not recognize that the user has other active organizations after login.
- Create two organizations and assign the same user/email to both;
- Inactivate the first organization created;
- Log in to the website.
> fix:  storefront permissions considers inactive organizations [KI 927174]

- CHANGELOG.md
- graphql/schema.graphql
Add validateStoreUserAccess to more APIs. More info: https://vtex-dev.atlassian.net/browse/B2BTEAM-1795
> fix: add validateStoreUserAccess to APIs

- CHANGELOG.md
- node/directives/withSession.ts
- node/metrics/session.ts
We currently have a lot of logs for "User not authenticated, make sure the query is private", which comes from the sessionData being null.
This PR adds a metric that allow us to understand where requests without sessionData are coming from.
We expect to reduce the number of logs and improve B2B Suite observability.
> fix: add with session metric

- CHANGELOG.md
- node/clients/index.ts
Provide app token on calls to b2b-organizations-graphql instead of admin/user tokens as these were already validated at this point. More details on: [https://vtex-dev.atlassian.net/browse/B2BTEAM-1796](https://vtex-dev.atlassian.net/browse/B2BTEAM-1796)
> fix: provide app token on calls to b2b-organizations-graphql

- CHANGELOG.md
- node/resolvers/Routes/index.ts
- node/yarn.lock
Add await to requests during login. This guarantees the user is associated to an active org, even if it is also part of inactive orgs. Otherwise, these requests might not complete before the active org is set to the user, ending up setting the wrong org (an inactive one).
> fix: add await to requests to properly handle login with inactive orgs

- CHANGELOG.md
- node/resolvers/Mutations/Users.ts
The `b2b_users` data on vbase was only being written but never read. This PR removes this entity usage from vbase.
This data was originally read on the `checkPermissions` function, but it was removed months ago due to an issue with vbase.
Now, this is the use cases that writes the most to vbase, but is its data is never read, hence, there is no point in keeping it.
> fix: remove unnecessary b2b_users storage on vbase

- CHANGELOG.md
- node/directives/validateStoreUserAccess.ts
- node/resolvers/Routes/index.ts
A bug has been identified during the Helmet House project, having to do with B2B impersonation. 
Part of the issue is that the `vtex_session` cookie has a longer expiration (~5 days) than the `VtexidClientAutCookie` (~1 day). Therefore, when returning to the store after 24 hours the user is likely to have an expired `VtexidClientAutCookie` but a non-expired session. 
If the user had an active B2B impersonation session when they last used the site, when they return their session will become corrupted due to Storefront-Permission's `setProfile` logic which does not expect this scenario. This can cause undesirable side effects; for example in Helmet House's case, the user is in a "half-logged in" state when they should actually be prompted to log in again …
> Session: return early if storeUserEmail is not populated

- CHANGELOG.md
- node/resolvers/Routes/index.ts
Adjusts the logic of the previous PR so as not to break VTEX "legacy" call center operator impersonation functionality. 
In the B2B impersonation scenario, the session provider must validate that the user has a `storeUserEmail` in their session -- in other words, they must be logged in to the storefront to be able to impersonate another B2B user.
In the legacy impersonation scenario, the user must be accessing `account.myvtex.com` as an admin user with the call center operator role, but not necessarily logged into the storefront. The `storeUserEmail` should not be validated in this case. 
New version linked and tested in https://arthur--helmethouseprod.myvtex.com
> Adjust session provider early return logic

- CHANGELOG.md
- node/resolvers/Mutations/Users.ts
We found a lot of error logs when the user already exists and someone tries to add the same email.
So, we removed the throwing to avoid excessive logs of errors treated.
Try to add an existing email user to the Buyer organization.
**Screenshots or example usage:**
> fix: Use return instead of throwing a duplicate email error.

- CHANGELOG.md
- node/resolvers/Mutations/Users.ts
- vtex.session/configuration.json
When the user changes organization right after placing an order, the session is not updated.
The PR consists of adding additional session control, forcing the session watcher to update the namespace values.
Also implemented a reusable retry functionality to updateSession
- Log in with a user that has more than one Organization/Cost Center
- Place an order
- Still, on the Order Placed page, change the Organization/Cost Center
- If there is an error, it won't update the selection (visible in the top bar)
> [FSEUS-521] Error changing Cost Center after placing order

- CHANGELOG.md
- node/package.json
- node/resolvers/Routes/index.ts
- node/yarn.lock
- vtex.session/configuration.json
A customer reported an issue where, after completing a purchase, attempting another purchase results in all items being removed from the cart at the checkout step.  
1. Go to the store login page.  
2. Log in with a test user.  
3. Add items to the cart (OrderFormId A).  
4. Go to checkout and complete the order (OrderPlaced page). A new `OrderFormId B` is generated automatically.  
5. From OrderPlaced, go back to home and add new items to the cart (OrderFormId B).  
6. Go to checkout. Items are displayed correctly initially.  
7. Proceed to the next step, and all items are removed.  
⚠️ **This issue is intermittent and does not occur for all users/accounts.**  
- Upon entering the checkout for the second time, `storefront-permissions` triggers a `SetProfile` API call.  
- Even though all …
> Fix: Prevent unnecessary cart clearing on checkout step

- .gitignore
- CHANGELOG.md
- graphql/schema.graphql
- node/mdSchema.ts
- node/resolvers/Mutations/Users.ts
- node/resolvers/Queries/Users.ts
- node/resolvers/Routes/index.ts
- node/resolvers/index.ts
This is a re-do of the [PR#178](https://github.com/vtex-apps/storefront-permissions/pull/178) that was reverted previously.
On top of what the original PR do, this change also:
* allows setting the user price table back to null
* fix a bug that would crash login if the organization had no associated price tables
* add the selectedPriceTable field on the response of user related queries.
Original PR description:
This feature allows storefront permissions app to set a custom priceTable based on user scope.
The mutation setCurrentPriceTable sets the selectedPriceTable field on b2b_users entity for the logged-in user.
The restriction in place is that the priceTable needs to be one of the user's organization "priceTables" field.
The Updated setProfile method …
> add: set user price table mutation
