- CHANGELOG.md
- docs/README.md
- react/components/userNew.tsx
- react/queries/SearchUsers.gql
- User search at the admin (Dependency change)
> Updated query due to changes on the dependency

- CHANGELOG.md
- docs/README.md
- graphql/schema.graphql
- node/resolvers/Queries/Roles.ts
- node/resolvers/index.ts
- new Graphql query `hasUsers`
> PERMISSION-8 Adding new query hasUsers

- CHANGELOG.md
- node/resolvers/Queries/Users.ts
- Exception for `vtex.storefront-permissions-ui` requests
> [PERMISSION-5] Added exeption for  requests

- CHANGELOG.md
- node/mdSchema.ts
- node/resolvers/Queries/Settings.ts
- node/resolvers/Queries/Users.ts
- node/resolvers/index.ts
- `viewUserPermission` couldn't find user email
> Fixing issue where viewUserPermission couldn't find an email

- node/resolvers/Queries/Settings.ts
> [USAAPPTEAM-75] Using VBase as alternative to app Settings

- CHANGELOG.md
- graphql/schema.graphql
- node/resolvers/Queries/Users.ts
- node/yarn.lock
Adds a Role ID parameter to the list User query so we may fetch a list of users with a specific role.
> B2BORG-28 Add users query by role id

- .github/workflows/lint.yml
- .github/workflows/sonarcloud.yml
- sonar-project.properties
Just adding quality engineering tasks.
> ADD Quality Engineering tasks

- CHANGELOG.md
- docs/README.md
- graphql/schema.graphql
- node/resolvers/Queries/Users.ts
- node/resolvers/index.ts
Added GraphQL query to return the Impersonated user information, will return null if none user is impersonated
> [PERMISSION-17] Added query to check impersonation

- CHANGELOG.md
- manifest.json
- node/resolvers/Mutations/Roles.ts
- node/resolvers/Queries/Roles.ts
- node/utils/index.ts
When I try to create a new user within a b2b organization, I see the name of the role showing multiple times.
**Solution**
- Changed the role handling from **masterdata** to **vbase** to avoid duplicated entries
Environment:
This fix is applied on:
[https://artur3--b2bstoreqa.myvtex.com/admin/storefront-permissions/roles/list](https://artur3--b2bstoreqa.myvtex.com/admin/storefront-permissions/roles/list)
[https://artur--vysk.myvtex.com/admin/storefront-permissions/roles/list](https://artur--vysk.myvtex.com/admin/storefront-permissions/roles/list)
> PERMISSION-19

- CHANGELOG.md
- docs/README.md
- manifest.json
- node/package.json
- node/yarn.lock
Elevated session error messages are being connected to an unnecessary dependency
Test can be made authenticating the user and checking the session facet still being update even without this dependency 
[https://wender--b2bstoreqa.myvtex.com/](https://wender--b2bstoreqa.myvtex.com/)
Kevin.yee@vtex.com
Vtex1234
> Removing unecessary dependencies; Adding additional information to DOC

- CHANGELOG.md
> Pumping a new version

- CHANGELOG.md
- node/resolvers/Mutations/Users.ts
Added a forgotten feature regarding the B2BORG-76 ticket. 
This feature provides a validation when the user is added checking if it exists on MD preventing duplicated entries.
It's linked on [https://b2borg--sandboxusdev.myvtex.com/](https://b2borg--sandboxusdev.myvtex.com/)
> B2BORG-76 - Validation if the user is already on MD

- CHANGELOG.md
- graphql/schema.graphql
- node/resolvers/Queries/Users.ts
- node/resolvers/index.ts
It was added into listUsers query the pagination approach in order to attend the[ [B2BORG-6]](https://github.com/vtex-apps/b2b-organizations/pull/38) requirements.
> [B2BORG-6] Organization storefront UI - Sales admin view

- CHANGELOG.md
- node/yarn.lock
- yarn.lock
`minimist` package updated from 1.2.5 to 1.2.7 due a critical security vulnerability
`#changingTooling`
> Engineers 829 fix sec vuln

- CHANGELOG.md
- cy-runner.yml
> Enable cypress video

- .github/workflows/qe-dispatch.yml
- .github/workflows/qe-pull-request-target.yml
- .github/workflows/qe-pull-request.yml
- .github/workflows/qe-schedule.yml
- CHANGELOG.md
- cy-runner.yml
- Cypress tests improvements
#changingTooling
> [ENGINEERS-975] - Cypress tests improvements

- CHANGELOG.md
- node/resolvers/Routes/index.ts
If no geoCoordinates is provided, set as an empty array
> Check geoCoordinates

- CHANGELOG.md
- node/resolvers/Routes/index.ts
An error was reported [here](https://github.com/vtex-apps/storefront-permissions/issues/110) because of a variable access that could be undefined.
@arturmagalhaesjr can you help me test this with the flow you implemented in https://github.com/vtex-apps/storefront-permissions/pull/108 ?
> Fix error when accessing undefined "cl" variable - Fixes #110

- CHANGELOG.md
- docs/README.md
Updated to: Store administrator, also known as a user who has access to the VTEX Admin, including the permission to impersonate any company/buyer.
It is solving a wrong description problem 
Better understanding of a funccionality 
No need
**Screenshots or example usage:**
No need.
> Store administration description update

- CHANGELOG.md
- graphql/schema.graphql
- node/resolvers/Queries/Users.ts
Add Filter OrgId and CostId in GetUsersByEmail
> Add Filter OrgId and CostId in GetUsersByEmail

- CHANGELOG.md
- node/directives/checkAdminAccess.ts
- node/directives/checkUserAccess.ts
Fix auth issue. See [B2BTEAM-1633](https://vtex-dev.atlassian.net/browse/B2BTEAM-1633) for more info.
[B2BTEAM-1633]: https://vtex-dev.atlassian.net/browse/B2BTEAM-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add additional check to admin token

- CHANGELOG.md
- node/clients/index.ts
Provide correct tokens to clients. More info: https://vtex-dev.atlassian.net/browse/B2BTEAM-1633
This is a follow-up PR to the previous security issue PR.
> fix: provide correct tokens to clients

- CHANGELOG.md
- node/directives/checkAdminAccess.ts
- node/directives/checkUserAccess.ts
- node/directives/helper.ts
- node/directives/validateStoreUserAccess.ts
- node/metrics/auth.ts
Add extra validations for admin and API tokens. More info on: [https://vtex-dev.atlassian.net/browse/B2BTEAM-1757](https://vtex-dev.atlassian.net/browse/B2BTEAM-1757)
> fix: admin and api token validation

- CHANGELOG.md
- graphql/directives.graphql
- graphql/schema.graphql
- node/directives/index.ts
- node/directives/validateAdminUserAccess.ts
Added a new admin validation directive. More info on: [https://vtex-dev.atlassian.net/browse/B2BTEAM-1744](https://vtex-dev.atlassian.net/browse/B2BTEAM-1744)
> fix: add new admin validation directive

- CHANGELOG.md
- graphql/schema.graphql
Changing the token validation directive of some operations. More info on: [https://vtex-dev.atlassian.net/browse/B2BTEAM-1755](https://vtex-dev.atlassian.net/browse/B2BTEAM-1755)
> fix: change validation directive of some operations

- CHANGELOG.md
- node/clients/checkout.ts
- node/package.json
- node/resolvers/Routes/index.ts
- node/yarn.lock
Products unavailable in the cart
- Create a user linked to this org: https://b2bstore005.myvtex.com/admin/b2b-organizations/organizations/125129e4-5bd0-11ef-b37f-e4b50a4acd8d/#/users
- Search for the "test" product in the search 
- Add to cart and check if it appears as available
**Screenshots or example usage:**
NOTE: for the product to appear as available in the search, the PR https://github.com/vtex-apps/b2b-theme/pull/11 must also be merged
> fix: [KI 1055033] - geocoordinates

- CHANGELOG.md
- graphql/schema.graphql
Add proper token validation to getUserByEmail.
> fix: add proper token validation to getUserByEmail

- .gitignore
- CHANGELOG.md
- graphql/schema.graphql
- node/mdSchema.ts
- node/resolvers/Mutations/Users.ts
- node/resolvers/Queries/Users.ts
- node/resolvers/Routes/index.ts
- node/resolvers/index.ts
This reverts commit 96237a4aed1db2dc5136ad50755f0f0a52ef0da7.
Version 1.46.0 has a bug and version was deprecated. So the commit included in it is being reverted.
> Revert "Feature/set pricetable mutation 2 (#178)"
